### ISSUE TITLE
Suggestion: main.gen_data function does not use "device" argument

### ISSUE THREAD

**Issue by AlexFridman** [kevinzakka/nca#1]

**Comment by kevinzakka** [comment]
The `gen_data` method is numpy only. This is so that PCA and any `sklearn` algorithm can use it directly. The NCA class does use the device arg though.

**Comment by AlexFridman** [comment]
So why do you have `device` argument in this function if it's unused? Maybe I should also add `device` argument to all my functions to confuse all people reading my code?

Did you get my point?

But, anyway - nice job! Thank you for the implementation!

**Comment by kevinzakka** [comment]
I completely misunderstood your original post, I apologize. Thanks for catching that actually, I'll take it out in the next commit.
