### ISSUE TITLE
X needs to be a torch tensor not ndarray

### ISSUE THREAD

**Issue by frenkiboy** [kevinzakka/nca#2]
https://github.com/kevinzakka/nca/blob/574cd402a2d28f38357e5451e7a2b453887eb90b/nca.py#L160

code breaks if ndarray input at X.is_cuda

**Comment by kevinzakka** [comment]
The docstring is incorrect, should be a torch tensor my bad! I'll update this in a bit!

**Comment by kevinzakka** [comment]
Fixed in newest commit.
