### ISSUE TITLE
error in distances * (~y_mask.int()).float()

### ISSUE THREAD

**Issue by frenkiboy** [kevinzakka/nca#3]
For some reason the code breaks in the following line:
    
    distances * (~y_mask.int()).float()

This is the code I use to run the embedding:
    
    Xten = torch.from_numpy(Xarr).double()
    yten = torch.from_numpy(yarr).int()

    emb = nca.NCA(dim=2, init="random")
    emb.train(Xten, yten, batch_size=64, normalize=False)

**Comment by frenkiboy** [comment]
Converting numpy array to float32 got it to run. The output is only NAN however:
epoch: 1 - loss: nan
epoch: 1 - loss: nan
epoch: 1 - loss: nan
epoch: 1 - loss: nan
epoch: 2 - loss: nan
epoch: 2 - loss: nan
epoch: 2 - loss: nan
epoch: 2 - loss: nan

....

**Comment by kevinzakka** [comment]
Hey @frenkiboy , could I get some more information about X_arr and y_arr?

y_mask should be a LongTensor when you feed it to the NCA train function and X_ten should be a FloatTensor.

I'd sometimes get `nan` if I set `normalize=True` in the train method when the data had already been normalized before-hand. The reason is that some feature variances may be 0 so you end up with zero division and pytorch silently converts to a `nan`.

**Comment by frenkiboy** [comment]
Dear Kevin, 

Thank you so much for the prompt response.
I've changed the code to the following:

    Xarr = Xpd.to_numpy().astype('float64')
    yarr = ypd.to_numpy().astype('long')

    Xten = torch.from_numpy(Xarr)
    yten = torch.from_numpy(yarr)

    emb = nca.NCA(dim=2, init="random")

    emb.train(Xten, yten, batch_size=64, normalize=True)

And get the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vfranke/Scripts/VR/NCA/nca/nca.py", line 202, in train
    loss = self.loss(X_batch, y_mask)
  File "/home/vfranke/Scripts/VR/NCA/nca/nca.py", line 97, in loss
    embedding = torch.mm(X, torch.t(self.A))
RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #2 'mat2' in call to _th_mm

The data:
https://drive.google.com/file/d/1OeKlVpgDlUrmoZ0fVoaPJBVzpjfMsfyk/view?usp=sharing

**Comment by kevinzakka** [comment]
Hey @frenkiboy,

Won't be free until the weekend. At first glance, your `X_arr` should be a FloatTensor (the equivalent in numpy is float32). So try something like `Xten = torch.from_numpy(Xarr).float()`
